apiVersion: v1
kind: "Service"
metadata:
  name: alertmanager
  namespace: jaden-test
  labels:
    name: alertmanager
spec:
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
  selector:
    app: alertmanager
  type: ClusterPort