apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: alertmanager
  name: alertmanager
  namespace: jaden-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: docker-registry.default.svc:5000/openshift/alertmanager:latest
        command:
        - "/bin/alertmanager"
        args:
        - "--config.file=/etc/alertmanager/alertmanager.yml"
        - "--storage.path=/alertmanager"
        ports:
        - containerPort: 9093
          protocol: TCP
        volumeMounts:
        - mountPath: "/etc/alertmanager"
          name: alertmanager-config
        - mountPath: "/alertmanager"
          name: alertmanager
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager
      - name: alertmanager
        persistentVolumeClaim:
          claimName: alertmanager