apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: jaden-test
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.qq.com:465'
      smtp_from: '3358765053@qq.com'
      smtp_auth_username: '3358765053@qq.com'
      smtp_auth_password: '*********'
      smtp_require_tls: false
    route:
      group_by: ['node_exporter', 'namespace']
      group_wait: 10s #分组持续时间，时间越长，获取的数据越多
      group_interval: 10s #分组间隔时间，时间越长，通知间隔越长
      repeat_interval: 1h
      receiver: 'non-receiver'
      routes:
      - match:
          node_exporter: true
        receiver: default-receiver

      #正则匹配namespace不为空的容器
      - match_re:
          namespace: .+
        receiver: default-receiver

      #匹配namespace为空的容器
      - match:
          namespace: 
        receiver: default-receiver
    receivers:
      - name: default-receiver
        email_configs:
          - to: xchduan@qingyuanos.com
            send_resolved: true
      - name: non-receiver
        email_configs:
          - to: 294339772@qq.com
            send_resolved: true
     # inhibit_rules:
     #   - source_match:
     #       severity: 'critical'
     #     target_match:
     #       severity: 'warning'
     #     equal: ['node_memory_alert', 'node_cpu_alert']