apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: jaden-test
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: smtp.qq.com:465
      smtp_from: 3358765053@qq.com
      smtp_auth_username: 3358765053@qq.com
      smtp_auth_password: d5885808
    route:
      group_by: ['nodealert']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'default-receiver'
    receivers:
      - name: default-receiver
        email_configs:
          - to: xchduan@qingyuanos.com
            send_resolved: true
    # inhibit_rules:
    #   - source_match:
    #       severity: 'critical'
    #     target_match:
    #       severity: 'warning'
    #     equal: ['node_memory_alert', 'node_cpu_alert']