apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rule
  namespace: jaden-test
data:
  prometheus.rules: |
    groups:
    - name: nodealert
      rules:
      - alert: container_memory_usage_bytes
        expr: container_memory_usage_bytes>1048576
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "container {{ $labels.pod_name }} memory usgae high"
          description: "{{ $labels.name }} memory usage above 1GB (current value: {{ $value }})"