apiVersion: v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: v1
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: jaden-test