apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: prometheus
  name: prometheus
  namespace: jaden-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      serviceAccount: prometheus
    spec:
      containers:
      - name: prometheus
        image: docker-registry.default.svc:5000/jaden-test/prometheus:v2.0.0
        command:
        - "/bin/prometheus"
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - mountPath: "/etc/prometheus"
          name: prometheus-rule-config
        - mountPath: "/etc/prometheus"
          name: prometheus-config
      volumes:
      - name: prometheus-rule-config
        configMap:
          name: prometheus-rule
      - name: prometheus-config
        configMap:
          name: prometheus