apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: jaden-test
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
      scrape_timeout: 30s
    rule_files:
      - "/etc/prometheus/rule/*.rules"
    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']
    - job_name: 'kubernetes-exporter-nodes'
      scheme: http
      static_configs: 
      - targets: ['172.28.90.77:31699']
    #alertmanager配置
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets: 
          - "alertmanager:9093"