apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rule
data:
  prometheus.rules: |
    groups:
    - name: noderecord
      rules:
      # The count of CPUs per node, useful for getting CPU time as a percent of total.
      - record: instance:node_cpus:count
        expr: count(node_cpu_seconds_total{mode="idle"}) without (cpu,mode)

      # CPU in use by CPU.
      - record: instance_cpu:node_cpu_seconds_not_idle:rate5m
        expr: sum(rate(node_cpu_seconds_total{mode!="idle"}[5m])) without (mode)

      # CPU in use by mode.
      - record: instance_mode:node_cpu_seconds:rate5m
        expr: sum(rate(node_cpu_seconds_total[5m])) without (cpu)

      # CPU in use ratio.
      - record: instance:node_cpu_utilization:ratio
        expr: sum(instance_mode:node_cpu_seconds:rate5m{mode!="idle"}) without (mode) / instance:node_cpus:count
    - name: nodealert
      rules:
      - alert: node_free_memory_lower
        expr: node_memory_MemFree_bytes/1073741824 < 1
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "node {{ $labels.__meat_kubernetes_pod_node_name }} free memory lower"
          description: "node {{ $labels.__meat_kubernetes_pod_node_name }} memory free below 1GB (current value: {{ $value }} GB)"
      - alert: node_cpu_load_high
        expr: node_load1 > 1
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "node {{ $labels.__meat_kubernetes_pod_node_name }} cpu load high"
          description: "node {{ $labels.__meat_kubernetes_pod_node_name }} cpu usage above 1 (current value: {{ $value }})"
      - alert: node_network_receive_speed_high
        expr: delta(node_network_receive_bytes_total{device="eth0"}[4s])/2097152 > 10
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "node {{ $labels.__meat_kubernetes_pod_node_name }} network receive speed high"
          description: "node {{ $labels.__meat_kubernetes_pod_node_name }} network receive speed above 10M (current value: {{ $value }} M/s)"
      - alert: node_network_transmit_speed_high
        expr: delta(node_network_transmit_bytes_total{device="eth0"}[4s])/2097152 > 10
        for: 5m
        labels:
          severity: page
        annotations:
          summary: "node {{ $labels.__meat_kubernetes_pod_node_name }} network transmit speed high"
          description: "node {{ $labels.__meat_kubernetes_pod_node_name }} network transmit speed above 10M (current value: {{ $value }} M/s)"
      # - alert: node_network_transmit_speed_high
      #   expr: delta(node_network_transmit_bytes_total{device="eth0"}[4s])/2097152 > 10
      #   for: 5m
      #   labels:
      #     severity: page
      #   annotations:
      #     summary: "node {{ $labels.__meat_kubernetes_pod_node_name }} network transmit speed high"
      #     description: "node {{ $labels.__meat_kubernetes_pod_node_name }} network transmit speed above 10M/s (current value: {{ $value }} M/s)"
      #- alert: container_memory_usage_bytes_high
      #  expr: container_memory_usage_bytes/1073741824 > 3
      #  for: 5m
      #  labels:
      #    severity: page
      #  annotations:
      #    summary: "container {{ $labels.__meat_kubernetes_pod_node_name }} memory usage high"
      #    description: "container {{ $labels.__meat_kubernetes_pod_node_name }} memory usage above 3GB (current value: {{ $value }} GB)"


